// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// kernel_norm_cpp
List kernel_norm_cpp(NumericVector K, arma::mat u, Nullable<IntegerVector> idx);
RcppExport SEXP _SPICER_kernel_norm_cpp(SEXP KSEXP, SEXP uSEXP, SEXP idxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type K(KSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type u(uSEXP);
    Rcpp::traits::input_parameter< Nullable<IntegerVector> >::type idx(idxSEXP);
    rcpp_result_gen = Rcpp::wrap(kernel_norm_cpp(K, u, idx));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SPICER_kernel_norm_cpp", (DL_FUNC) &_SPICER_kernel_norm_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_SPICER(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
