# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

kernel_norm_cpp <- function(K, u, idx = NULL) {
    .Call(`_SPICER_kernel_norm_cpp`, K, u, idx)
}

